# Generated by Django 5.1.3 on 2025-03-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produitcommande',
            name='montant',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
