# Generated by Django 5.1.3 on 2025-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0002_commande_montant_total_produitcommande_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
