# Generated by Django 5.1.3 on 2025-03-24 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='ancien_prix',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.categorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_desc', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.produit')),
            ],
        ),
    ]
