# Generated by Django 5.1.3 on 2025-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_produit_ancien_prix_produit_categorie_produit_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='ancien_prix',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
