# Generated by Django 5.1.3 on 2025-05-18 00:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
